export const HEARTBEAT_INTERVAL_SECONDS = 5;
export const HEARTBEAT_LOST_THRESHOLD_MS = 12_000;

export const MAX_KEYSTROKE_DETAIL_ROWS = 10_000;
export const MAX_WINDOW_DETAIL_ROWS = 5_000;
export const MAX_CLIPBOARD_DETAIL_ROWS = 5_000;
